name: 0\{11\}
url: http://blog.undicizeri.com
description: What the fuck am I reading!?

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']